# -*- coding: utf-8 -*-
"""toolcrib_predictive

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Gn_s95mLnxYpzlaCCsahDsMMdVB8vqc
"""

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from prophet import Prophet
import warnings

# Mengabaikan warning Prophet agar terminal server tetap bersih
warnings.filterwarnings('ignore')

class ToolCribPredictiveEngine:
    def __init__(self):
        """
        Inisialisasi mesin prediktif.
        Model NLP langsung dimuat saat mesin dinyalakan (agar lebih cepat saat dipanggil API berulang).
        """
        print("⚙️ Memulai Mesin Prediktif ToolCrib AI...")
        self.nlp_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
        print("✅ Model NLP Semantik berhasil dimuat.")

    def calculate_abc_xyz_and_minmax(self, df_sku: pd.DataFrame, df_trx: pd.DataFrame) -> pd.DataFrame:
        """
        Mengkategorikan barang (ABC/XYZ) dan menghitung Dynamic Min-Max.
        """
        # 1. Klasifikasi ABC
        usage_df = df_trx.groupby('SKU_ID')['Quantity_Issued'].sum().reset_index()
        usage_df.columns = ['SKU_ID', 'Total_Qty_Yearly']

        df_analysis = pd.merge(usage_df, df_sku[['SKU_ID', 'Description', 'Unit_Price', 'Lead_Time_Days']], on='SKU_ID')
        df_analysis['Total_Value'] = df_analysis['Total_Qty_Yearly'] * df_analysis['Unit_Price']
        df_analysis = df_analysis.sort_values(by='Total_Value', ascending=False).reset_index(drop=True)

        df_analysis['Cum_Percent'] = df_analysis['Total_Value'].cumsum() / df_analysis['Total_Value'].sum()
        df_analysis['ABC_Class'] = df_analysis['Cum_Percent'].apply(
            lambda pct: 'A' if pct <= 0.80 else ('B' if pct <= 0.95 else 'C')
        )

        # 2. Klasifikasi XYZ
        df_trx['Date'] = pd.to_datetime(df_trx['Date'])
        monthly_demand = df_trx.groupby(['SKU_ID', df_trx['Date'].dt.to_period('M')])['Quantity_Issued'].sum().reset_index()

        stats_df = monthly_demand.groupby('SKU_ID')['Quantity_Issued'].agg(['mean', 'std']).reset_index().fillna(0)
        stats_df['CV'] = stats_df['std'] / stats_df['mean']
        stats_df['XYZ_Class'] = stats_df['CV'].apply(
            lambda cv: 'X' if cv <= 0.5 else ('Y' if cv <= 1.0 else 'Z')
        )

        # 3. Dynamic Min-Max
        df_final = pd.merge(df_analysis, stats_df[['SKU_ID', 'XYZ_Class']], on='SKU_ID')
        df_final['Daily_Demand'] = df_final['Total_Qty_Yearly'] / 365
        df_final['Dynamic_Min_ROP'] = np.ceil((df_final['Daily_Demand'] * df_final['Lead_Time_Days']) * 1.5)
        df_final['Dynamic_Max'] = df_final['Dynamic_Min_ROP'] + np.ceil(df_final['Daily_Demand'] * 30)

        return df_final[['SKU_ID', 'Description', 'ABC_Class', 'XYZ_Class', 'Dynamic_Min_ROP', 'Dynamic_Max', 'Unit_Price', 'Total_Qty_Yearly']]

    def detect_duplicate_sku(self, df_sku: pd.DataFrame, threshold: float = 0.60) -> pd.DataFrame:
        """
        Mencari indikasi barang duplikat menggunakan Semantic Word Embeddings.
        """
        descriptions = df_sku['Description'].tolist()
        sku_ids = df_sku['SKU_ID'].tolist()

        # Mengubah teks menjadi vektor dan menghitung jaraknya
        embeddings = self.nlp_model.encode(descriptions)
        similarity_matrix = cosine_similarity(embeddings)

        duplicate_pairs = []
        for i in range(len(sku_ids)):
            for j in range(i + 1, len(sku_ids)):
                if similarity_matrix[i][j] >= threshold:
                    duplicate_pairs.append({
                        'SKU_1': sku_ids[i],
                        'Desc_1': descriptions[i],
                        'SKU_2': sku_ids[j],
                        'Desc_2': descriptions[j],
                        'Similarity_Score': round(similarity_matrix[i][j] * 100, 1)
                    })

        return pd.DataFrame(duplicate_pairs)

    def forecast_stock(self, df_trx: pd.DataFrame, target_sku: str, days_ahead: int = 30) -> pd.DataFrame:
        """
        Memprediksi kebutuhan stok di masa depan menggunakan Prophet.
        """
        df_target = df_trx[df_trx['SKU_ID'] == target_sku].copy()
        if df_target.empty:
            return pd.DataFrame()

        df_daily = df_target.groupby('Date')['Quantity_Issued'].sum().reset_index()
        df_daily.columns = ['ds', 'y']
        df_daily['ds'] = pd.to_datetime(df_daily['ds'])

        model = Prophet(daily_seasonality=True, yearly_seasonality=False, weekly_seasonality=True)
        model.fit(df_daily)

        future = model.make_future_dataframe(periods=days_ahead)
        forecast = model.predict(future)

        forecast['yhat'] = forecast['yhat'].clip(lower=0)
        forecast['yhat_lower'] = forecast['yhat_lower'].clip(lower=0)

        return forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(days_ahead)